"""db migrations

Revision ID: 70224c9d1ff1
Revises: fb47c7c3d1b3
Create Date: 2026-08-12 23:45:34.377516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70224c9d1ff1'
down_revision: Union[str, Sequence[str], None] = 'fb47c7c3d1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_file_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'uploaded_files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comparisons_previous_report_id_fkey'), 'comparisons', type_='foreignkey')
    op.drop_constraint(op.f('comparisons_new_report_id_fkey'), 'comparisons', type_='foreignkey')
    op.drop_constraint(op.f('comparisons_user_id_fkey'), 'comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'comparisons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comparisons', 'report_details', ['previous_report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comparisons', 'report_details', ['new_report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('report_details_file_id_fkey'), 'report_details', type_='foreignkey')
    op.create_foreign_key(None, 'report_details', 'uploaded_files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uploaded_files_user_id_fkey'), 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(None, 'uploaded_files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(op.f('uploaded_files_user_id_fkey'), 'uploaded_files', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'report_details', type_='foreignkey')
    op.create_foreign_key(op.f('report_details_file_id_fkey'), 'report_details', 'uploaded_files', ['file_id'], ['id'])
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.create_foreign_key(op.f('comparisons_user_id_fkey'), 'comparisons', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('comparisons_new_report_id_fkey'), 'comparisons', 'report_details', ['new_report_id'], ['id'])
    op.create_foreign_key(op.f('comparisons_previous_report_id_fkey'), 'comparisons', 'report_details', ['previous_report_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_file_id_fkey'), 'chats', 'uploaded_files', ['file_id'], ['id'])
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
