"""db migrations

Revision ID: 9020f3cf97de
Revises: 70224c9d1ff1
Create Date: 2026-08-14 00:04:27.002577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9020f3cf97de'
down_revision: Union[str, Sequence[str], None] = '70224c9d1ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('key_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('comparisons', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('comparisons', sa.Column('follow_up', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_details', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('report_details', sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_details', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_details', sa.Column('follow_up', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('report_details', 'summary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_details', sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('report_details', 'follow_up')
    op.drop_column('report_details', 'recommendations')
    op.drop_column('report_details', 'key_findings')
    op.drop_column('report_details', 'summary')
    op.drop_column('comparisons', 'follow_up')
    op.drop_column('comparisons', 'recommendations')
    op.drop_column('comparisons', 'key_changes')
    # ### end Alembic commands ###
