"""db migrations

Revision ID: fb47c7c3d1b3
Revises: 
Create Date: 2026-08-11 15:04:44.528819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb47c7c3d1b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_msg', sa.Text(), nullable=False),
    sa.Column('ai_msg', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_file_id'), 'chats', ['file_id'], unique=False)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('report_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('hemoglobin', sa.Float(), nullable=True),
    sa.Column('wbc_count', sa.Float(), nullable=True),
    sa.Column('platelet_count', sa.Float(), nullable=True),
    sa.Column('blood_sugar', sa.Float(), nullable=True),
    sa.Column('hba1c', sa.Float(), nullable=True),
    sa.Column('total_cholesterol', sa.Float(), nullable=True),
    sa.Column('hdl_cholesterol', sa.Float(), nullable=True),
    sa.Column('ldl_cholesterol', sa.Float(), nullable=True),
    sa.Column('triglycerides', sa.Float(), nullable=True),
    sa.Column('creatinine', sa.Float(), nullable=True),
    sa.Column('egfr', sa.Float(), nullable=True),
    sa.Column('ast_sgot', sa.Float(), nullable=True),
    sa.Column('alt_sgpt', sa.Float(), nullable=True),
    sa.Column('tsh', sa.Float(), nullable=True),
    sa.Column('vitamin_d', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_report_details_id'), 'report_details', ['id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('previous_report_id', sa.Integer(), nullable=False),
    sa.Column('new_report_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['new_report_id'], ['report_details.id'], ),
    sa.ForeignKeyConstraint(['previous_report_id'], ['report_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_id'), 'comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_comparisons_new_report_id'), 'comparisons', ['new_report_id'], unique=False)
    op.create_index(op.f('ix_comparisons_previous_report_id'), 'comparisons', ['previous_report_id'], unique=False)
    op.create_index(op.f('ix_comparisons_user_id'), 'comparisons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparisons_user_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_previous_report_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_new_report_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_report_details_id'), table_name='report_details')
    op.drop_table('report_details')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_file_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
